workflows:
   main-workflow:
     name: IELTS & SAT Prep App CI/CD
     instance_type: mac_mini_m1
     max_build_duration: 30
     
     environment:
       flutter: stable
       java: 17
       
     cache:
       cache_paths:
         - ~/.pub-cache
         - .gradle
         
     triggering:
       events:
         - push
         - pull_request
       branch_patterns:
         - pattern: main
           include: true
           source: true
           
     scripts:
       - name: Install Flutter dependencies
         script: |
           flutter pub get
           
       - name: Build Android APK
         script: |
           flutter build apk --release --no-shrink
             
     artifacts:
       - build/**/outputs/**/*.apk
